### ISSUE TITLE
Turn into library

### ISSUE THREAD

**Issue by HelloGrayson** [Barzahlen/waitforservices#4]
Would like to use this directly from another Go lib - possible in turning this into a lib?

**Comment by tobischo** [comment]
Yes, it is. Since we do not need this right now, we probably won't pursue it. You are very welcome to make a pull request though with the interface you had in mind for it.
If you do, please follow the general pattern that has established for golang code, where the lib is in the root of the repository and cmd/<name> for a main package to keep it go-get-able as CLI tool

**Comment by HelloGrayson** [comment]
SGTM.
